CONTIKI = ../..
all: app

CONTIKIDIRS += $(CONTIKI)/libsync $(CONTIKI)/liblog $(CONTIKI)/libdata $(CONTIKI)/libbird
PROJECT_SOURCEFILES += dclock.c birdlog.c birddata.c birdtrace.c

include $(CONTIKI)/Makefile.include
